// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkzrlayykgfxflvrncfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrenJsYXl5a2dmeGZsdnJuY2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDE4ODksImV4cCI6MjA1OTc3Nzg4OX0.KjdokrbW2yVgMd6f52xTHOL4cPfjvGeuChTi_p_4nU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);